version: '3'
services:
  ### Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["server"]

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:2.8.0-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_API_URL=${PREFECT_API_HOST}/api
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["server"]

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.8.0-python3.11
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["agent"]

  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.8.0-python3.11
    entrypoint: "bash"
    working_dir: "/root/"
    volumes:
      - "./flows:/root/flows"
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["cli"]

  ### Metabase DB
  metabase_db:
    image: postgres
    environment:
      - POSTGRES_DB=${MB_POSTGRES_DB}
      - POSTGRES_USER=${MB_POSTGRES_USER}
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGPORT=6432
    ports:
      - 6432:6432
    volumes:
      - mbdb:/var/lib/postgresql/data
    profiles: ["metabase"]

  ### Metabase_app
  metabase_app:
    image: metabase/metabase
    ports:
      - 3000:3000
    depends_on:
      - metabase_db
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_PORT=6432
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_HOST=metabase_db
    volumes:
      - metabase:/metabase-data
    profiles: ["metabase"]

  dbt-docs:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.4.0
    volumes:
      - .:/root/dbt
      - ~/.dbt:/root/.dbt
    working_dir: /root/dbt/de_zoomcamp
    environment:
      - DBT_PROFILES_DIR=/root/.dbt
      - DBT_PROFILE=de-zoomcamp
      - DBT_PROJECT_DIR=/root/dbt/de-zoomcamp
    ports:
      - 8080:8080
    entrypoint: ["dbt", "docs", "serve"]
    profiles: ["dbt-docs"]

volumes:
  prefect:
  db:
  mbdb:
  metabase:
networks:
  default:
    name: prefect-network