import pyarrow as pa

schema_green = pa.schema([
    pa.field("vendor_id", pa.int64(), True),
    pa.field("lpep_pickup_datetime", pa.timestamp('us'), True),
    pa.field("lpep_dropoff_datetime", pa.timestamp('us'), True),
    pa.field("trip_distance", pa.float64(), True),
    pa.field("ratecode_id", pa.int64(), True),
    pa.field("store_and_fwd_flag", pa.string(), True),
    pa.field("pu_location_id", pa.int64(), True),
    pa.field("do_location_id", pa.int64(), True),
    pa.field("payment_type", pa.int64(), True),
    pa.field("fare_amount", pa.float64(), True),
    pa.field("extra", pa.float64(), True),
    pa.field("mta_tax", pa.float64(), True),
    pa.field("tip_amount", pa.float64(), True),
    pa.field("tolls_amount", pa.float64(), True),
    pa.field("improvement_surcharge", pa.float64(), True),
    pa.field("total_amount", pa.float64(), True),
    pa.field("congestion_surcharg", pa.float64(), True),
    pa.field("trip_type", pa.int64(), True),
    pa.field("ehail_fee", pa.string(), True),
    pa.field("passenger_count", pa.int64(), True),
])
schema_yellow = pa.schema([
    pa.field("vendor_id", pa.int64(), True),
    pa.field("tpep_pickup_datetime", pa.timestamp('us'), True),
    pa.field("tpep_dropoff_datetime", pa.timestamp('us'), True),
    pa.field("trip_distance", pa.float64(), True),
    pa.field("ratecode_id", pa.int64(), True),
    pa.field("store_and_fwd_flag", pa.string(), True),
    pa.field("pu_location_id", pa.int64(), True),
    pa.field("do_location_id", pa.int64(), True),
    pa.field("payment_type", pa.int64(), True),
    pa.field("fare_amount", pa.float64(), True),
    pa.field("extra", pa.float64(), True),
    pa.field("mta_tax", pa.float64(), True),
    pa.field("tip_amount", pa.float64(), True),
    pa.field("tolls_amount", pa.float64(), True),
    pa.field("improvement_surcharge", pa.float64(), True),
    pa.field("total_amount", pa.float64(), True),
    pa.field("congestion_surcharg", pa.float64(), True),
    pa.field("passenger_count", pa.int64(), True),
])

service_columns =  { 'fhv': {'column_types': {'dispatching_base_num': 'str',
                                      'pickup_datetime': 'datetime64',
                                      'drop_off_datetime': 'datetime64',
                                      'pu_location_id': 'Int64',
                                      'do_location_id': 'Int64',
                                      'sr_flag': 'Int64',
                                      'affiliated_base_number': 'str'},
                             'parquet_schema': None},
                     'yellow': {'column_types': {'vendor_id': 'Int64',
                                                 'tpep_pickup_datetime': 'datetime64',
                                                 'tpep_dropoff_datetime': 'datetime64',
                                                 'passenger_count': 'Int64',
                                                 'trip_distance': 'float',
                                                 'ratecode_id': 'Int64',
                                                 'store_and_fwd_flag': 'string',
                                                 'pu_location_id': 'Int64',
                                                 'do_location_id': 'Int64',
                                                 'payment_type': 'Int64',
                                                 'fare_amount' : 'float',
                                                 'extra' : 'float',
                                                 'mta_tax' : 'float',
                                                 'tip_amount' : 'float',
                                                 'tolls_amount' : 'float',
                                                 'improvement_surcharge' : 'float',
                                                 'total_amount' : 'float',
                                                 'congestion_surcharg' : 'float'},
                                 'parquet_schema': 'schema_yellow'},
                     'green': {'column_types': {'vendor_id': 'Int64',
                                                'lpep_pickup_datetime': 'datetime64',
                                                'lpep_dropoff_datetime': 'datetime64',
                                                'store_and_fwd_flag': 'string',
                                                'ratecode_id': 'Int64',
                                                'pu_location_id': 'Int64',
                                                'do_location_id': 'Int64',
                                                'passenger_count': 'Int64',
                                                'trip_distance': 'float',
                                                'fare_amount' : 'float',
                                                'extra' : 'float',
                                                'mta_tax' : 'float',
                                                'tip_amount' : 'float',
                                                'tolls_amount' : 'float',
                                                'ehail_fee': 'string',
                                                'improvement_surcharge' : 'float',
                                                'total_amount' : 'float',
                                                'payment_type': 'Int64',
                                                'trip_type': 'Int64',
                                                'congestion_surcharg' : 'float'},
                                'parquet_schema': 'schema_green'}
                     }
